# Generated by Django 3.2.6 on 2021-08-28 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urfavmovie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favmovie',
            name='directorName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='favmovie',
            name='posters',
            field=models.ImageField(default='', upload_to='urfavmovie\\images'),
        ),
        migrations.AddField(
            model_name='favmovie',
            name='ratingImdb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favmovie',
            name='releaseDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
